services:
  api:
    build: .
    ports:
      - "80:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/db
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
